### ISSUE TITLE
Migrate Jimmy to Huxley

### ISSUE THREAD

**Issue by addersuk** [simplybusiness/jimmy#47]
**BLOCKED:** As public repo do not have access to AWS secrets in github.
## What

We need to migrate to Huxley, this will be our first gem using Huxley.

## Why

Jenkins is eventually going away, so we can create a GitHub Actions workflow that we can then rollout to all the other private gems.

## How

Most gems use multiple steps to create the gem, but i would suggest we do this as one stage to limit the impact of the slow step startup.

Therefore we can do all the following as a single stage:

- build gem
- check semaphore (might not be needed)
- publish to BNW Registry
- generate release notes

## ACs

- [ ] We have a GitHub Action Workflow for production that publishes the production ready gem with release notes
- [ ] We have a GitHub Action Workflow for branches that publishes a pre-release gem 
- [ ] The pipeline takes similar time to the current Jenkins pipeline

**Comment by punitcse** [comment]
Closing this as we have created a new  card #50
